version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    env_file: .env
    container_name: app_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
